AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru
    - config/initializers/**/*
    - config/environments/**/*